sonar.projectKey=mrplCMSProject
sonar.projectName=mrplCMS
sonar.projectVersion=1.0

sonar.sources=source
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.ts,__tests__/**/*.test.tsx
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/ios/Pods/**,**/android/build/**,**/coverage/**,**/*.d.ts
sonar.coverage.exclusions=source/app/navigation/types.ts
sonar.typescript.tsconfigPath=tsconfig.sonar.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
